blank_issues_enabled: true
contact_links:
  - name: GitHub nikGimp Support
    url: https://github.com/iiey/nikGimp/discussions
    about: Please ask and answer questions here.
  - name: Report a bug
    url: https:/github.com/iiey/nikGimp/issues
    about: Please report bugs here.